uint8 BOOL=0
uint8 INT=1
uint8 FLOAT=2
uint8 DOUBLE=3
uint8 STRING=4
uint8 VBOOL=5
uint8 VINT=6
uint8 VFLOAT=7
uint8 VDOUBLE=8
uint8 VSTRING=9
uint8 POSE=10
uint8 TF=11
uint8 STATICTF=12
uint8 VPOSE=13
uint8 VTF=14
uint8 ERROR=15
uint8 NUM_TYPES=16

uint8 type

bool bool_value false
int32 int_value 0
float32 float_value 0.0
float64 double_value 0.0
string string_value ""
geometry_msgs/PoseStamped pose_value
geometry_msgs/TransformStamped tf_value

bool[] bool_vector
int32[] int_vector
float32[] float_vector
float64[] double_vector
string[] string_vector
geometry_msgs/PoseStamped[] pose_vector
geometry_msgs/TransformStamped[] tf_vector
